### ISSUE TITLE
Uncaught Error: Template parse errors: Can't bind to 'featureToggleService' since it isn't a known property of 'feature-toggle-provider'

### ISSUE THREAD

**Issue by ashashree14** [willmendesneto/ngx-feature-toggle#89]
**I'm submitting a bug report**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

Uncaught Error: Template parse errors:
Can't bind to 'featureToggleService' since it isn't a known property of 'feature-toggle-provider'

**Expected behavior**

Should hide a button when feature-toggle is false

**Reproduction of the problem**

Just follow https://github.com/willmendesneto/ngx-feature-toggle/blob/master/README.md .
use ngx-feature-toggle(4.0.0)
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Operating system: Ubuntu 14.04 
* **Browser:** [ Chrome 58  ]

* **Language:** [TypeScript 2.3.4, angular 4]

* **Node (if applicable):** `node --version` =  v6.10.0
`npm --version` = 3.10.10

**Comment by willmendesneto** [comment]
Hi @ashashree14 . Could you provide more details about this issue? 

I'm trying to simulate it locally, but I couldn't. If you can share a plunkr link or similar with this issue will be good to fix as well.

**Comment by willmendesneto** [comment]
Closing this issue by lack of response. Thanks @ashashree14
